### ISSUE TITLE
Tracking issue for documentation

### ISSUE THREAD

**Issue by ubnt-intrepid** [finchers-rs/guide#1]
### Homepage
- [x] at `finchers-rs.github.io`

### Book
- [x] Initialize (mdbook)
- [ ] Sections
  - [x] Quickstart
  - [ ] Writing a Finchers Application
  - [ ] The Structure of Finchers Web application
    - [ ] `Endpoint` / `Task`
    - [ ] `Responder`
  - [ ] Launching the HTTP service
  - [ ] Cookbook (if needed)
